EFCoreHotel_RazorPages/Models/Hotel.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EFCoreHotel_RazorPages.Models
{
    [Table("Hotel")]
    public partial class Hotel
    {
        public Hotel()
        {
            Rooms = new HashSet<Room>();
        }

        [Key]
        [Column("Hotel_No")]
        public int HotelNo { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Address { get; set; }

        public int? RoomCount { get; set; }

        [InverseProperty(nameof(Room.HotelNoNavigation))]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}

EFCoreHotel_RazorPages/Pages/Hotels/GetHotels.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using EFCoreHotel_RazorPages.HotelDBContext;
using EFCoreHotel_RazorPages.Models;
using EFCoreHotel_RazorPages.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Query;

namespace EFCoreHotel_RazorPages
{
    public class GetHotelsModel : PageModel
    {
        public int Bookings { get; set; }
        [BindProperty(SupportsGet = true)]
        [Required]
        public String HotelName { get; set; }
        [Required]
        [BindProperty(SupportsGet = true)]
        public DateTime DateTime { get; set; }
        public double Income { get; set; }
        public IEnumerable<Hotel> Hotels { get; set; }
        public IEnumerable<Room> Rooms { get; set; }
        IHotelService hotelService;
        private IBookingService bookingService;
        public GetHotelsModel(IHotelService service, IBookingService service1)
        {
            hotelService = service;
            bookingService = service1;

        }
        public void OnGet()
        {
            Hotels = hotelService.GetHotels();

            if (ModelState.IsValid)
            {
                Income = hotelService.GetSpecificDayIncome(HotelName, DateTime);
            }
        }

        public void OnPostPrindsen()
        {
            Hotels = hotelService.GetHotels();
            Bookings = bookingService.GetBookinsPerHotel();
        }
    }
}

EFCoreHotel_RazorPages/Pages/Hotels/HotelDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EFCoreHotel_RazorPages.Models;
using EFCoreHotel_RazorPages.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EFCoreHotel_RazorPages.Pages.Hotels
{
    public class HotelDetailsModel : PageModel
    {
        public IEnumerable<Room> Rooms { get; set; }
        [BindProperty]
        public string HotelName { get; set; }
        public int RoomCount { get; set; }
        IRoomService roomService;
        public HotelDetailsModel(IRoomService service)
        {
            roomService= service;
        }
        public IActionResult OnGet(int hotelNo, string hotelName, int roomCount)
        {
            Rooms = roomService.GetRoomByHotelNo(hotelNo);
            HotelName = hotelName;//Spagueti way to get the hotel name and room count
            RoomCount = roomCount;

            return Page();
        }
    }
}

EFCoreHotel_RazorPages/Pages/Hotels/HotelDetails_RoomInfo.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EFCoreHotel_RazorPages.Models;
using EFCoreHotel_RazorPages.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EFCoreHotel_RazorPages.Pages.Hotels
{
    public class HotelDetails_RoomInfoModel : PageModel
    {
        
        public IEnumerable<Booking> Bookings { get; set; }
        private IBookingService bookingService;

        public HotelDetails_RoomInfoModel(IBookingService service)
        {
            bookingService = service;
        }

        public void OnGet(int roomid, int hotelid)
        {
            Bookings = bookingService.GetBookingInfo(roomid, hotelid);
        }
    }
}

EFCoreHotel_RazorPages/Pages/Hotels/GetHotels.cshtml
@page
@using EFCoreHotel_RazorPages.Models
@using EFCoreHotel_RazorPages.Services.Interface
@model EFCoreHotel_RazorPages.GetHotelsModel
@{
    ViewData["Title"] = "GetHotels";
}

<h1>List of Hotels</h1>
<h2>Income calculator</h2>
<table class="table">
    <thead>
    <tr>
        Input the specific day, and the hotel name to get the total income for all bookings on that specific day
    </tr>
    </thead>
</table>
<form>
    <div class="form-group">
        Date: <input class="form-control" asp-for="DateTime" />
    </div>
    <div class="form-group">
        <input asp-for="@Model.HotelName" placeholder="HotelName" class="form-control" />
    </div>
    Total Income :  @Model.Income
    <div class="form-group">
        <input type="submit" value="Get Income" class="btn btn-primary"/>
    </div>
</form>
<h3> Prindsen March Bookings</h3>
<form method="post">
    <div class="form-group">
        <input type="submit" value="Get Prindsen March Bookings" class="btn btn-primary" asp-page-handler="Prindsen" />
    </div>
    Prindsen Bookings : @Model.Bookings
</form>
<table class="table">
    <thead>
        <tr>
            <th> Hotel Id  </th>
            <th> Name </th>
            <th> Address  </th>
            <th> </th>
            <th> Total Room Count</th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Hotels != null)
        {

            @foreach (var item in Model.Hotels)
            {

                <tr>
                    <td>@item.HotelNo  </td>
                    <td>  @item.Name </td>
                    <td>  @item.Address </td>
                    <td><a asp-route-roomCount="@item.RoomCount" asp-route-hotelName="@item.Name" asp-route-hotelNo="@item.HotelNo" asp-page="HotelDetails">All Rooms</a></td>
                    <td>@item.RoomCount</td>
                </tr>
            }
        }
</table>

EFCoreHotel_RazorPages/Pages/Hotels/HotelDetails.cshtml
@page
@using EFCoreHotel_RazorPages.Services.Interface
@model EFCoreHotel_RazorPages.Pages.Hotels.HotelDetailsModel
@{
}


<h1>Details of @Model.HotelName ---- Total of Rooms -> @Model.RoomCount</h1>
<table class="table">
    <thead>
        <tr>
            <th> Room No  </th>
            <th> Hotel No </th>
            <th> Room Type  </th>
            <th> Price </th>
        </tr>
    </thead>
    <tbody>

        @if (Model.Rooms != null)
        {
            @foreach (var item in Model.Rooms)
            {
                <tr>
                    <td>@item.RoomNo  </td>
                    <td>  @item.HotelNo </td>
                    <td>  @item.Types </td>
                    <td> @item.Price</td>
                     <td><a asp-route-roomid="@item.RoomNo"asp-route-hotelid="@item.HotelNo" asp-page="HotelDetails_RoomInfo">Room Bookings Info</a></td>
                </tr>
            }
        }
</table>

EFCoreHotel_RazorPages/Pages/Hotels/HotelDetails_RoomInfo.cshtml
@page
@model EFCoreHotel_RazorPages.Pages.Hotels.HotelDetails_RoomInfoModel
@{
}

<h4 style="color:red"> List of bookings</h4>
<table class="table">
    <thead>
    <tr>
        <th> Booking Id  </th>
        <th> From  </th>
        <th> To  </th>
        <th> Guest Name </th>
        <th> Guest Address</th>
       
    </tr>
    </thead>
    <tbody>

    @if (Model.Bookings != null)
    {
        @foreach (var item in Model.Bookings)
        {
            <tr>
                <td>  @item.BookingId</td>     
                <td>  @item.DateFrom  </td>
                <td>  @item.DateTo </td>
                <td>  @item.Guest.Name </td>
                <td>  @item.Guest.Address</td>
                
            </tr>
        }
    }
</table>